export const TECH_LABELS = {
  html5: "HTML",
  css3: "CSS",
  javascript: "Javascript",
  typescript: "Typescript",
  python: "Python",
  react: "React",
  vue: "Vue",
  next: "Next",
  astro: "Astro",
  sass: "SASS",
  tailwindcss: "TailwindCSS",
  styledcomponents: "Styled Components",
  node: "Node",
  docker: "Docker",
  postgresql: "PostgreSQL",
  mongodb: "MongoDB",
  jest: "Jest",
  vitest: "Vitest",
  testinglibrary: "Testing Library",
  cypress: "Cypress",
  git: "Git",
  github: "GitHub",
  githubactions: "GitHub Actions",
  figma: "Figma",
};
